
name: 'dbt_product_warehouse'
version: '0.0.1'
config-version: 2

profile: 'dbt_product_warehouse'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
