
name: 'dbt_product_warehouse'
version: '0.0.1'
require-dbt-version: ">=0.17.0"
config-version: 2

profile: dbt_product_warehouse

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

vars:
  cdp: segment
  cdp-pages-table: "{{ source('segment', 'pages') }}"
  cdp-tracks-table: "{{ source('segment', 'pages') }}"
  cdp-users-table: "{{ source('segment', 'users') }}"
  sessions-base-model: segment_web_sessions

models:
  dbt_product_warehouse:
    staging:
      materialized: view
      schema: staging
    integration:
      materialized: view
      schema: staging
    warehouses:
      materialized: table
