- name: segment
    database: segment
    schema: product

    freshness:
      warn_after: {count: 1, period: day}
      error_after: {count: 2, period: day}

    loaded_at_field: timestamp

    tables:
      - name: pages
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: tracks
        columns:
          - name: id
            tests:
              - unique
              - not_null
