version: 2

sources:
  - name: segment
    database: segment_events
    schema: javascript

    freshness:
      warn_after: {count: 1, period: day}

    loaded_at_field: uuid_ts

    tables:
      - name: pages
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: tracks
        columns:
          - name: id
            tests:
              - unique
              - not_null
